%% APFC_Parameters.m
% Parameter initialisation script for the APFC simulation models.
%
% Run this script once at the start of each MATLAB session, before opening
% or simulating any model. Every parameter used by the Simulink models is
% computed here, at full double precision, and placed in the base
% workspace, so no numerical value is typed into a block (report
% Section 4.2.4).
%
% Parameter categories:
%   Category 1 - Analytically derived: computed from first principles.
%   Category 2 - Numerically solved: either recomputed by calling a
%                dedicated script (motor) or loaded from a .mat file
%                produced by a design script (ALPF). In both cases no
%                solver output is typed in as a literal.
%
% Folder structure assumed (relative to this script's folder):
%   02 - Motor\  APFC_WEG_W22_IE3_30kW_Parameter_Estimation_Lee_et_al.m
%   03 - ALPF\01 - LPF\  ALPF_LPF_Coefficients.mat
%   03 - ALPF\02 - FAP\  ALPF_FAP_Coefficients.mat
%   03 - ALPF\04 - Tables\  ALPF_Tables.mat
%   04 - FLC\  APFC_FLC.fis (generated by build_APFC_FLC.m)
%
% The ALPF files are required by every model, including those without the
% ALPF, because the 12.5 kHz measurement sample rate (ALPF_fs) is read from
% ALPF_LPF_Coefficients.mat.
%
% Project : Fuzzy Logic-Controlled Automatic Power Factor Correction Using
%           Thyristor-Switched Capacitor Banks for a 30 kW Induction Motor
% Author  : Praise Oluwasina Akinlolu, Department of Electrical and
%           Electronics Engineering, University of Lagos
% MATLAB  : R2025b
% Licence : MIT (see LICENSE in the repository root)

%% -- Resolve script location -------------------------------------------------
scriptDir = fileparts(mfilename('fullpath'));

%% ============================================================================
%  CATEGORY 1 - ANALYTICALLY DERIVED PARAMETERS
%% ============================================================================

%% System Parameters
f       = 50;
omega   = 2 * pi * f;
V_line  = 415;
V_phase = V_line / sqrt(3);

%% TSC Subsystem
p   = 0.06;
R_d = 1e5;
Q_reactor = 12.5;  % Design decision

C_B1 = 5e3  / (3 * V_line^2 * omega);
C_B2 = 10e3 / (3 * V_line^2 * omega);
C_B3 = 20e3 / (3 * V_line^2 * omega);

L_B1 = p / (omega^2 * C_B1);
L_B2 = p / (omega^2 * C_B2);
L_B3 = p / (omega^2 * C_B3);

%% ALPF - Offset increments (analytically derived; Category 1)
% Patent integers 300 (offset-fine, state ST3) and 4000 (offset-gross,
% state ST4) of Dossi (US 12,294,375 B2) are fractions of the patent's
% 2^23 full-scale digital swing. They are rescaled here to the peak phase
% voltage V_peak = V_phase*sqrt(2) = 338.8460811 V, because the ALPF in
% this project operates on the actual phase voltage (report Section 3.5.5).
ALPF_V_peak           = V_phase * sqrt(2);
ALPF_offset_inc_fine  = 300  * ALPF_V_peak / 2^23;   % ST3 increment (V/cycle)
ALPF_offset_inc_gross = 4000 * ALPF_V_peak / 2^23;   % ST4 increment (V/cycle)

%% Fuzzy logic controller (report Sections 3.5.6 to 3.5.9)
fis = readfis(fullfile(scriptDir, '04 - FLC' ,'APFC_FLC.fis'));
FLC_deadband_kVAR = 3;   % design choice: anti-hunt hold-band half-width (kVAr)
                         % lower bound = half the smallest bank = 2.5 kVAr

tau_Qload = 3;   % DESIGN DECISION: time constant (s) of the low-pass filter on
                 % the reconstructed reactive demand Q_load (report Section 3.6.2).
                 % Much longer than the ~1 s hunting period it suppresses, much
                 % shorter than the 50 s run. Native continuous LPF 1/(tau*s+1).

%% ============================================================================
%  CATEGORY 2A - MOTOR PARAMETERS (recomputed from nameplate data)
%  Calls the Lee et al. (2012) estimation script directly (report
%  Sections 3.4.2 to 3.4.6). That script does not call clc or clear, so
%  the workspace built so far is preserved.
%  Outputs deposited: R1, X1, R2, X2, XM, Rc, s, VRated, J_motor
%% ============================================================================

motor_script = fullfile(scriptDir, '02 - Motor', ...
    'APFC_WEG_W22_IE3_30kW_Parameter_Estimation_Lee_et_al.m');

if ~isfile(motor_script)
    error(['Missing motor parameter script:\n  %s\n' ...
           'Check folder structure.'], motor_script);
end

run(motor_script);

%% -- Consistency check: V_phase (Category 1) must equal VRated (motor script)
% Both quantities are the per-phase RMS voltage (415/sqrt(3)).
% They are computed independently; agreement confirms no nameplate mismatch.
V_phase_motor_error = abs(V_phase - VRated);
if V_phase_motor_error > 1e-10
    error(['CONSISTENCY FAILURE: V_phase = %.15f V (Category 1) ' ...
           'differs from VRated = %.15f V (motor script) ' ...
           'by %.4e V. Check VLL in motor script vs V_line here.'], ...
          V_phase, VRated, V_phase_motor_error);
else
    fprintf('Consistency check PASSED: V_phase = VRated = %.10f V\n', V_phase);
end

%% Motor operating-point powers (reference values; not used by the models)
% Equivalent-circuit evaluation at the three load points. Slip is scaled
% linearly with load fraction (s_75 = 0.75*s, s_50 = 0.50*s), which gives
% shaft speeds of 1485, 1488.75 and 1492.5 rpm at 100, 75 and 50 % load.
s_load  = [1.00, 0.75, 0.50] * s;                 % 100 / 75 / 50% load slips
Z_shunt = 1 ./ (1/Rc + 1./(1i*XM));               % core-loss || magnetising
P_op = zeros(1,3);  Q_op = zeros(1,3);
for k = 1:3
    Z_rotor = R2./s_load(k) + 1i*X2;
    Z_in    = (R1 + 1i*X1) + (Z_shunt.*Z_rotor)./(Z_shunt + Z_rotor);
    I1      = V_phase / Z_in;
    S3      = 3 * V_phase * conj(I1);             % three-phase complex power
    P_op(k) = real(S3);
    Q_op(k) = imag(S3);
end
P_100 = P_op(1);  Q_100 = Q_op(1);
P_75  = P_op(2);  Q_75  = Q_op(2);
P_50  = P_op(3);  Q_50  = Q_op(3);

%% ============================================================================
%  CATEGORY 2B - ALPF PARAMETERS (loaded from verified .mat files)
%% ============================================================================

%% ALPF - Low-pass filter stage
LPF_mat = fullfile(scriptDir, '03 - ALPF', '01 - LPF', ...
                   'ALPF_LPF_Coefficients.mat');
if ~isfile(LPF_mat)
    error('Missing: %s\nRun ALPF_LPF_Design.m first.', LPF_mat);
end
tmp            = load(LPF_mat, 'sos', 'g', 'fs', 'phase_50Hz', 'mag_50Hz');
ALPF_LPF_sos   = tmp.sos;
ALPF_LPF_g     = tmp.g;
ALPF_fs        = tmp.fs;
ALPF_LPF_phi50 = tmp.phase_50Hz;
ALPF_LPF_mag50 = tmp.mag_50Hz;

% -- Magnitude compensation (derived; Category 2B) ----------------------------
% ALPF_LPF_mag50 is stored in decibels (ALPF_LPF_Design.m, Section 5:
% mag_50Hz = 20*log10(abs(h))). The voltage-normalising gain of the
% ALPF-present model (APFC_FullModel_v21b_Qmeas) needs the linear passband
% magnitude, so it is converted once, here. The FAP and AAP stages are
% all-pass (|H| = 1), so the LPF magnitude is the entire ALPF passband
% attenuation at 50 Hz. Not referenced by the models without the ALPF.
ALPF_LPF_mag50_lin = 10^(ALPF_LPF_mag50/20);   % linear |H_LPF(50)| ≈ 0.987794103168737

%% ALPF - Fixed all-pass (FAP) stage
FAP_mat = fullfile(scriptDir, '03 - ALPF', '02 - FAP', ...
                   'ALPF_FAP_Coefficients.mat');
if ~isfile(FAP_mat)
    error('Missing: %s\nRun ALPF_FAP_Design.m first.', FAP_mat);
end
tmp            = load(FAP_mat, 'FAP');
ALPF_FAP       = tmp.FAP;
ALPF_FAP_alpha = tmp.FAP.alpha;
ALPF_FAP_b     = tmp.FAP.b;
ALPF_FAP_a     = tmp.FAP.a;
ALPF_FAP_phi50 = tmp.FAP.phi_at_50Hz;

%% ALPF - Gross and fine lookup tables
Tables_mat = fullfile(scriptDir, '03 - ALPF', '04 - Tables', ...
                      'ALPF_Tables.mat');
if ~isfile(Tables_mat)
    error('Missing: %s\nRun ALPF_Tables_Design.m first.', Tables_mat);
end
tmp                   = load(Tables_mat, 'Tables');
ALPF_Tables           = tmp.Tables;

% Guard: confirm the loaded .mat carries the expected field set (fails clearly if stale)
req_fields = {'alpha_gross','phi_gross','alpha_fine_delta', ...
              'k_powerOn','gross_step_deg','dphi_fine_deg'};
missing    = req_fields(~isfield(ALPF_Tables, req_fields));
if ~isempty(missing)
    error(['ALPF_Tables.mat is missing expected field(s): %s\n' ...
           'Regenerate via ALPF_Tables_Design.m.'], strjoin(missing, ', '));
end

ALPF_gross_alpha      = tmp.Tables.alpha_gross;        % 80 gross coefficients
ALPF_gross_phi        = tmp.Tables.phi_gross;          % 80 gross target phases (deg)
ALPF_fine_alpha_delta = tmp.Tables.alpha_fine_delta;   % 80 per-OP signed delta-alpha
ALPF_dphi_fine        = tmp.Tables.dphi_fine_deg;      % uniform fine phase step (deg)
ALPF_k_powerOn        = tmp.Tables.k_powerOn;          % power-on index (40)
ALPF_gross_step       = tmp.Tables.gross_step_deg;     % gross step (1.125 deg)

%% ============================================================================
%  HARMONIC CAMPAIGN PARAMETERS (report Section 3.6.4)
%% ============================================================================
% Fixed order superset injected via the Voltage Source (Three-Phase) 'Source
% harmonics' field. Each test cell is defined PURELY by H_ratios (magnitude of
% each order relative to the fundamental). Inactive orders carry ratio 0.
H_orders = [2 3 5 7 11 13];     % additional orders (fundamental auto-prepended)
H_ratios = [0 0 0 0 0 0];       % DEFAULT = clean grid; overridden per test cell

% IEEE-519 TDD reference current: maximum demand load current, taken as the
% motor rated current from the WEG W22 IE3 datasheet. Fixed across all load
% points (report Section 4.4.3). Used in post-processing only.
I_L = 56.4;                      % A

%% Output-domain low-pass filter on the P and Q outputs (report Section 3.5.4)
fc_dq   = 5;                    % DESIGN DECISION: P and Q low-pass cutoff (Hz)
tau_dq  = 1/(2*pi*fc_dq);       % continuous 1st-order LPF time constant (s)
Ts_meas = 1/ALPF_fs;            % measurement discrete rate (s) = 1/12500 = 80 us
a_dq    = exp(-Ts_meas/tau_dq); % discrete pole (exact continuous-pole match)
b_dq    = 1 - a_dq;             % numerator, unity DC gain

%% -- Final confirmation printout ---------------------------------------------
fprintf('\n=== APFC_Parameters.m — Load Complete ===\n');
fprintf('System:  f = %.0f Hz, V_line = %.0f V, omega = %.6f rad/s\n', ...
        f, V_line, omega);
fprintf('TSC:     C_B1 = %.6e F, L_B1=%.6e H\n', C_B1, L_B1);
fprintf('         C_B2 = %.6e F, L_B2=%.6e H\n', C_B2, L_B2);
fprintf('         C_B3 = %.6e F, L_B3=%.6e H\n', C_B3, L_B3);
fprintf('Motor:   R1 = %.10f Ohm\n', R1);
fprintf('         X1 = %.10f Ohm\n', X1);
fprintf('         R2 = %.10f Ohm\n', R2);
fprintf('         X2 = %.10f Ohm\n', X2);
fprintf('         XM = %.10f Ohm\n', XM);
fprintf('         Rc = %.10f Ohm\n', Rc);
fprintf('         s = %.10f\n',     s);
fprintf('         J = %.10f kg.m^2\n', J_motor);
fprintf('ALPF:    fs = %.0f Hz\n', ALPF_fs);
fprintf('         phi_LPF(50Hz) = %.4f deg\n', ALPF_LPF_phi50);
fprintf('         alpha_FAP   = %.10f\n', ALPF_FAP_alpha);
fprintf('         phi_FAP(50Hz) = %.4f deg\n', ALPF_FAP_phi50);
fprintf('         k_powerOn   = %d\n', ALPF_k_powerOn);
fprintf('         gross_step  = %.6f deg\n', ALPF_gross_step);
fprintf('         dphi_fine   = %.8f deg\n', ALPF_dphi_fine);
fprintf('         offset_inc_fine = %.8f V/cycle\n', ALPF_offset_inc_fine);
fprintf('         offset_inc_gross = %.8f V/cycle\n', ALPF_offset_inc_gross);
fprintf('         FLC fis loaded\n ')
fprintf('=========================================\n');